name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    if: github.repository == 'brc-dd/parcel-watcher'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - run: |
          pnpm i
          pnpm tsdown --minify
          rm README.md
          npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
